spring:
 application:
  name: db-service
 cloud:
    config:
      discovery:
        enabled: true
        #serviceId: db-service
        
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}    
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrl: https://${eureka.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
    metadataMap:
       hostname: ${eureka.instance.hostname}
       securePort: ${server.port}  