spring:
  application:
    name: zuul-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761}/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      service-id: DB-SERVICE
      #url: https://db-service1234.cfapps.io/rest/db/sam
    #stock-service:
      #path: /stock-service/**
      #service-id: STOCK-SERVICE
      #url: http://localhost:8301